### PR TITLE
[MaxGuiTextareaScintilla.mod] Add support for "caret line"

### PR DESCRIPTION
**Pull request by GWRon**
Adds support to enable and colorize the line at which the caret is currently

### CODE REVIEW

**Comment by GWRon** [comment]
The caret line is only visible for active windows - so if your MaxIDE looses focus (eg a popup window opens when making a screenshot or so) then the line is no longer colored.

One could set options for this but I think the behaviour suits here.

**Comment by woollybah** [comment]
What colour do you get on the line whilst debugging?

**Comment by GWRon** [comment]
That is a different setting.

This line here is to show where your caret is while editing.

Am 6. Mai 2019 17:39:29 MESZ schrieb Brucey <notifications@github.com>:

**Comment by GWRon** [comment]
I could add some more options - but every little option added in the style of the latest additions means to add stub methods to _every_ `TGadget` (instead of some TTextareaGadget ... or an interface).

For debugging: it should highlight the line already (of course in the non-attention-crying color you've choosen for your "current line"-background) as the caret is positioned at the error-line.


what do you think - is the "error colored"-variant needed too?

**Pull request merged**
